version: '3.4'

services:
  backend:
    build: .
    container_name: backend
    entrypoint: sh -c "pipenv run python manage.py collectstatic --no-input && pipenv run gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - "8000"
    volumes:
      - ./:/app/
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static/:/static/
    depends_on:
      - backend
    restart: always