# Generated by Django 4.0.6 on 2022-07-22 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, verbose_name='상태')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='삭제시간')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('hashtags_text', models.TextField(verbose_name='해시태그')),
                ('view_count', models.IntegerField(verbose_name='조회수')),
                ('like_count', models.IntegerField(verbose_name='좋아요수')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='post.status', verbose_name='상태')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
