# Generated by Django 4.0.6 on 2022-07-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_postlike_postlike_unique_user_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='is_like',
            field=models.BooleanField(default=True, verbose_name='좋아요'),
        ),
    ]
