# Generated by Django 4.0.6 on 2022-07-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='이메일 주소')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('nickname', models.CharField(max_length=20, unique=True, verbose_name='닉네임')),
                ('username', models.CharField(max_length=20, verbose_name='이름')),
                ('profile_image', models.ImageField(default='user/static/profile/default_profile_image.jpg', upload_to='user/static/profile/', verbose_name='프로필 사진')),
                ('introduce', models.CharField(default='안녕하세요~', max_length=200, verbose_name='소개')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='휴대폰 번호')),
                ('date_of_birth', models.DateField(verbose_name='생년월일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성여부')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
